
[2021-05-22 01:41:18,572]
{'errors': [],
 'id': None,
 'metadata': None,
 'response': {'category': 'masterdata',
              'logs': None,
              'operation': 'insert',
              'status': 'FAILED',
              'statusDescription': '[org.springframework.batch.item.file.FlatFileParseException: '
                                   'Parsing error at line: 2 in '
                                   'resource=[InputStream resource [resource '
                                   'loaded through InputStream]], '
                                   'input=[110011,5402120055,110011,11011@philsys.gov.ph,123,ACT,10039,eng,NULL,PWD,TRUE]\n'
                                   '\tat o]',
              'successCount': 0,
              'tableName': 'user_detail_h',
              'timeStamp': '2021-05-21T20:11:18.580724',
              'transcationId': '63566477-6256-4ffe-bf8f-4236f5c87ff7',
              'uploadedBy': 'lalith'},
 'responsetime': '2021-05-21T20:11:18.403Z',
 'version': None}

[2021-05-22 01:41:19,366]
{'errors': [],
 'id': None,
 'metadata': None,
 'response': {'category': 'masterdata',
              'logs': None,
              'operation': 'insert',
              'status': 'FAILED',
              'statusDescription': '[io.mosip.admin.packetstatusupdater.exception.RequestException: '
                                   'ADM-BLK-003 --> Duplicate Record\n'
                                   '\tat '
                                   'io.mosip.admin.config.RepositoryListItemWriter.doWrite(RepositoryListItemWriter.java:87)\n'
                                   '\tat '
                                   'io.mosip.admin.config.RepositoryListItemWriter.write(Repo]',
              'successCount': 69,
              'tableName': 'template',
              'timeStamp': '2021-05-21T20:11:19.371506',
              'transcationId': '59220bce-9468-47b0-9f8a-d1f93f72c480',
              'uploadedBy': 'lalith'},
 'responsetime': '2021-05-21T20:11:19.120Z',
 'version': None}

[2021-05-22 01:41:19,786]
{'errors': [],
 'id': None,
 'metadata': None,
 'response': {'category': 'masterdata',
              'logs': None,
              'operation': 'insert',
              'status': 'COMPLETED',
              'statusDescription': None,
              'successCount': 3,
              'tableName': 'individual_type',
              'timeStamp': '2021-05-21T20:11:19.795337',
              'transcationId': '635fcaa7-e5fb-4ad0-9051-9fd7f0ce2854',
              'uploadedBy': 'lalith'},
 'responsetime': '2021-05-21T20:11:19.604Z',
 'version': None}

[2021-05-22 01:41:20,198]
{'errors': [],
 'id': None,
 'metadata': None,
 'response': {'category': 'masterdata',
              'logs': None,
              'operation': 'insert',
              'status': 'COMPLETED',
              'statusDescription': None,
              'successCount': 1,
              'tableName': 'appl_form_type',
              'timeStamp': '2021-05-21T20:11:20.203312',
              'transcationId': '3c1c456b-6669-4b2c-b4d4-b789ce96bd79',
              'uploadedBy': 'lalith'},
 'responsetime': '2021-05-21T20:11:20.026Z',
 'version': None}

[2021-05-22 01:41:20,618]
{'errors': [],
 'id': None,
 'metadata': None,
 'response': {'category': 'masterdata',
              'logs': None,
              'operation': 'insert',
              'status': 'FAILED',
              'statusDescription': '[io.mosip.admin.packetstatusupdater.exception.RequestException: '
                                   'ADM-BLK-003 --> Duplicate Record\n'
                                   '\tat '
                                   'io.mosip.admin.config.RepositoryListItemWriter.doWrite(RepositoryListItemWriter.java:87)\n'
                                   '\tat '
                                   'io.mosip.admin.config.RepositoryListItemWriter.write(Repo]',
              'successCount': 1,
              'tableName': 'biometric_type',
              'timeStamp': '2021-05-21T20:11:20.612550',
              'transcationId': '00165b3b-1c7c-4a01-8e03-50e2d08771dc',
              'uploadedBy': 'lalith'},
 'responsetime': '2021-05-21T20:11:20.438Z',
 'version': None}

[2021-05-22 01:41:20,890]
{'errors': [{'errorCode': 'ADM-BLK-002',
             'message': 'invalid field mentioned.The exception occured at line '
                        'number 1'}],
 'id': None,
 'metadata': None,
 'response': None,
 'responsetime': '2021-05-21T20:11:20.934Z',
 'version': None}

[2021-05-22 01:41:21,263]
{'errors': [],
 'id': None,
 'metadata': None,
 'response': {'category': 'masterdata',
              'logs': None,
              'operation': 'insert',
              'status': 'FAILED',
              'statusDescription': '[io.mosip.admin.packetstatusupdater.exception.RequestException: '
                                   'ADM-BLK-003 --> Duplicate Record\n'
                                   '\tat '
                                   'io.mosip.admin.config.RepositoryListItemWriter.doWrite(RepositoryListItemWriter.java:87)\n'
                                   '\tat '
                                   'io.mosip.admin.config.RepositoryListItemWriter.write(Repo]',
              'successCount': 1,
              'tableName': 'zone',
              'timeStamp': '2021-05-21T20:11:21.271311',
              'transcationId': '485f7d59-62cf-47f9-a2aa-3dc7f3916b93',
              'uploadedBy': 'lalith'},
 'responsetime': '2021-05-21T20:11:21.130Z',
 'version': None}

[2021-05-22 01:41:21,916]
{'errors': [],
 'id': None,
 'metadata': None,
 'response': {'category': 'masterdata',
              'logs': None,
              'operation': 'insert',
              'status': 'FAILED',
              'statusDescription': '[io.mosip.kernel.core.dataaccess.exception.DataAccessLayerException: '
                                   'KER-DAH-001 --> '
                                   'org.hibernate.exception.ConstraintViolationException: '
                                   'could not execute statement; \n'
                                   'nested exception is '
                                   'javax.persistence.PersistenceException: '
                                   'org.hibernate.exceptio]',
              'successCount': 1,
              'tableName': 'zone_user_h',
              'timeStamp': '2021-05-21T20:11:21.928445',
              'transcationId': '57c07b76-6f77-402b-91fd-5db07644ba63',
              'uploadedBy': 'lalith'},
 'responsetime': '2021-05-21T20:11:21.777Z',
 'version': None}

[2021-05-22 01:41:22,167]
{'errors': [{'errorCode': 'ADM-BLK-002',
             'message': 'invalid field mentioned.The exception occured at line '
                        'number 1'}],
 'id': None,
 'metadata': None,
 'response': None,
 'responsetime': '2021-05-21T20:11:22.212Z',
 'version': None}

[2021-05-22 01:41:22,569]
{'errors': [],
 'id': None,
 'metadata': None,
 'response': {'category': 'masterdata',
              'logs': None,
              'operation': 'insert',
              'status': 'FAILED',
              'statusDescription': '[io.mosip.kernel.core.dataaccess.exception.DataAccessLayerException: '
                                   'KER-DAH-001 --> '
                                   'org.hibernate.exception.ConstraintViolationException: '
                                   'could not execute statement; \n'
                                   'nested exception is '
                                   'javax.persistence.PersistenceException: '
                                   'org.hibernate.exceptio]',
              'successCount': 1,
              'tableName': 'valid_document',
              'timeStamp': '2021-05-21T20:11:22.577737',
              'transcationId': 'c9194ef3-639f-45a1-86c6-7fd61ad32f22',
              'uploadedBy': 'lalith'},
 'responsetime': '2021-05-21T20:11:22.403Z',
 'version': None}

[2021-05-22 01:41:23,002]
{'errors': [],
 'id': None,
 'metadata': None,
 'response': {'category': 'masterdata',
              'logs': None,
              'operation': 'insert',
              'status': 'COMPLETED',
              'statusDescription': None,
              'successCount': 1,
              'tableName': 'template_type',
              'timeStamp': '2021-05-21T20:11:23.002436',
              'transcationId': 'abb5e1c4-ef6f-45b0-b2aa-b0a0b4673528',
              'uploadedBy': 'lalith'},
 'responsetime': '2021-05-21T20:11:22.807Z',
 'version': None}

[2021-05-22 01:41:23,413]
{'errors': [],
 'id': None,
 'metadata': None,
 'response': {'category': 'masterdata',
              'logs': None,
              'operation': 'insert',
              'status': 'COMPLETED',
              'statusDescription': None,
              'successCount': 3,
              'tableName': 'gender',
              'timeStamp': '2021-05-21T20:11:23.417342',
              'transcationId': '0e140c81-5fba-4fef-97b5-b118f481a144',
              'uploadedBy': 'lalith'},
 'responsetime': '2021-05-21T20:11:23.239Z',
 'version': None}

[2021-05-22 01:41:23,870]
{'errors': [],
 'id': None,
 'metadata': None,
 'response': {'category': 'masterdata',
              'logs': None,
              'operation': 'insert',
              'status': 'FAILED',
              'statusDescription': '[io.mosip.kernel.core.dataaccess.exception.DataAccessLayerException: '
                                   'KER-DAH-001 --> '
                                   'org.hibernate.exception.ConstraintViolationException: '
                                   'could not execute statement; \n'
                                   'nested exception is '
                                   'javax.persistence.PersistenceException: '
                                   'org.hibernate.exceptio]',
              'successCount': 50,
              'tableName': 'registration_center',
              'timeStamp': '2021-05-21T20:11:23.879204',
              'transcationId': '32fc4ca7-5d21-4b1a-b829-fba248eb6a51',
              'uploadedBy': 'lalith'},
 'responsetime': '2021-05-21T20:11:23.658Z',
 'version': None}

[2021-05-22 01:41:24,245]
{'errors': [],
 'id': None,
 'metadata': None,
 'response': {'category': 'masterdata',
              'logs': None,
              'operation': 'insert',
              'status': 'FAILED',
              'statusDescription': '[io.mosip.kernel.core.dataaccess.exception.DataAccessLayerException: '
                                   'KER-DAH-001 --> '
                                   'org.hibernate.exception.ConstraintViolationException: '
                                   'could not execute statement; \n'
                                   'nested exception is '
                                   'javax.persistence.PersistenceException: '
                                   'org.hibernate.exceptio]',
              'successCount': 1,
              'tableName': 'registration_center',
              'timeStamp': '2021-05-21T20:11:24.255046',
              'transcationId': '28a55a93-c635-42c0-9220-252d58ab914f',
              'uploadedBy': 'lalith'},
 'responsetime': '2021-05-21T20:11:24.107Z',
 'version': None}

[2021-05-22 01:41:24,487]
{'errors': [{'errorCode': 'ADM-BLK-002',
             'message': 'invalid field mentioned.The exception occured at line '
                        'number 1'}],
 'id': None,
 'metadata': None,
 'response': None,
 'responsetime': '2021-05-21T20:11:24.532Z',
 'version': None}

[2021-05-22 01:41:24,884]
{'errors': [],
 'id': None,
 'metadata': None,
 'response': {'category': 'masterdata',
              'logs': None,
              'operation': 'insert',
              'status': 'COMPLETED',
              'statusDescription': None,
              'successCount': 1,
              'tableName': 'language',
              'timeStamp': '2021-05-21T20:11:24.887317',
              'transcationId': '1f84111f-15ee-4b9e-8075-a987d3e0d927',
              'uploadedBy': 'lalith'},
 'responsetime': '2021-05-21T20:11:24.723Z',
 'version': None}

[2021-05-22 01:41:25,327]
{'errors': [{'errorCode': 'ADM-BLK-002',
             'message': 'invalid field mentioned.The exception occured at line '
                        'number 1'}],
 'id': None,
 'metadata': None,
 'response': None,
 'responsetime': '2021-05-21T20:11:25.371Z',
 'version': None}

[2021-05-22 01:41:25,704]
{'errors': [],
 'id': None,
 'metadata': None,
 'response': {'category': 'masterdata',
              'logs': None,
              'operation': 'insert',
              'status': 'FAILED',
              'statusDescription': '[io.mosip.kernel.core.dataaccess.exception.DataAccessLayerException: '
                                   'KER-DAH-001 --> '
                                   'org.hibernate.exception.ConstraintViolationException: '
                                   'could not execute statement; \n'
                                   'nested exception is '
                                   'javax.persistence.PersistenceException: '
                                   'org.hibernate.exceptio]',
              'successCount': 14,
              'tableName': 'reg_working_nonworking',
              'timeStamp': '2021-05-21T20:11:25.718712',
              'transcationId': '03b1eb00-1530-4317-82a8-d92674bd6d81',
              'uploadedBy': 'lalith'},
 'responsetime': '2021-05-21T20:11:25.563Z',
 'version': None}

[2021-05-22 01:41:26,114]
{'errors': [],
 'id': None,
 'metadata': None,
 'response': {'category': 'masterdata',
              'logs': None,
              'operation': 'insert',
              'status': 'FAILED',
              'statusDescription': '[io.mosip.kernel.core.dataaccess.exception.DataAccessLayerException: '
                                   'KER-DAH-001 --> '
                                   'org.hibernate.exception.ConstraintViolationException: '
                                   'could not execute statement; \n'
                                   'nested exception is '
                                   'javax.persistence.PersistenceException: '
                                   'org.hibernate.exceptio]',
              'successCount': 1,
              'tableName': 'location',
              'timeStamp': '2021-05-21T20:11:26.105600',
              'transcationId': '80a71c02-c307-44f4-a6bf-63dd74502d55',
              'uploadedBy': 'lalith'},
 'responsetime': '2021-05-21T20:11:25.941Z',
 'version': None}

[2021-05-22 01:41:26,776]
{'errors': [],
 'id': None,
 'metadata': None,
 'response': {'category': 'masterdata',
              'logs': None,
              'operation': 'insert',
              'status': 'FAILED',
              'statusDescription': '[javax.persistence.PersistenceException: '
                                   'org.hibernate.exception.SQLGrammarException: '
                                   'could not extract ResultSet\n'
                                   '\tat '
                                   'org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:149)\n'
                                   '\tat '
                                   'org.hibernate.internal.ExceptionConverterI]',
              'successCount': 1,
              'tableName': 'registration_center_h',
              'timeStamp': '2021-05-21T20:11:26.788830',
              'transcationId': 'ae70741f-6fae-4f16-a77b-195a19aa8aef',
              'uploadedBy': 'lalith'},
 'responsetime': '2021-05-21T20:11:26.627Z',
 'version': None}

[2021-05-22 01:41:27,030]
{'errors': [{'errorCode': 'ADM-BLK-002',
             'message': 'invalid field mentioned.The exception occured at line '
                        'number 1'}],
 'id': None,
 'metadata': None,
 'response': None,
 'responsetime': '2021-05-21T20:11:27.074Z',
 'version': None}

[2021-05-22 01:41:27,440]
{'errors': [],
 'id': None,
 'metadata': None,
 'response': {'category': 'masterdata',
              'logs': None,
              'operation': 'insert',
              'status': 'FAILED',
              'statusDescription': '[io.mosip.kernel.core.dataaccess.exception.DataAccessLayerException: '
                                   'KER-DAH-001 --> '
                                   'org.hibernate.exception.ConstraintViolationException: '
                                   'could not execute statement; \n'
                                   'nested exception is '
                                   'javax.persistence.PersistenceException: '
                                   'org.hibernate.exceptio]',
              'successCount': 3,
              'tableName': 'machine_master',
              'timeStamp': '2021-05-21T20:11:27.422655',
              'transcationId': 'cf679281-2c5f-4502-b1b2-1a37b6f79317',
              'uploadedBy': 'lalith'},
 'responsetime': '2021-05-21T20:11:27.266Z',
 'version': None}

[2021-05-22 01:41:27,905]
{'errors': [],
 'id': None,
 'metadata': None,
 'response': {'category': 'masterdata',
              'logs': None,
              'operation': 'insert',
              'status': 'FAILED',
              'statusDescription': '[io.mosip.admin.packetstatusupdater.exception.RequestException: '
                                   'ADM-BLK-003 --> Duplicate Record\n'
                                   '\tat '
                                   'io.mosip.admin.config.RepositoryListItemWriter.doWrite(RepositoryListItemWriter.java:87)\n'
                                   '\tat '
                                   'io.mosip.admin.config.RepositoryListItemWriter.write(Repo]',
              'successCount': 7,
              'tableName': 'biometric_attribute',
              'timeStamp': '2021-05-21T20:11:27.881112',
              'transcationId': '4205efd1-20ce-4c63-aa34-c1d327cc7820',
              'uploadedBy': 'lalith'},
 'responsetime': '2021-05-21T20:11:27.679Z',
 'version': None}

[2021-05-22 01:41:28,160]
{'errors': [{'errorCode': 'ADM-BLK-002',
             'message': 'invalid field mentioned.The exception occured at line '
                        'number 1'}],
 'id': None,
 'metadata': None,
 'response': None,
 'responsetime': '2021-05-21T20:11:28.204Z',
 'version': None}

[2021-05-22 01:41:28,541]
{'errors': [],
 'id': None,
 'metadata': None,
 'response': {'category': 'masterdata',
              'logs': None,
              'operation': 'insert',
              'status': 'FAILED',
              'statusDescription': '[io.mosip.admin.packetstatusupdater.exception.RequestException: '
                                   'ADM-BLK-003 --> Duplicate Record\n'
                                   '\tat '
                                   'io.mosip.admin.config.RepositoryListItemWriter.doWrite(RepositoryListItemWriter.java:87)\n'
                                   '\tat '
                                   'io.mosip.admin.config.RepositoryListItemWriter.write(Repo]',
              'successCount': 3,
              'tableName': 'doc_category',
              'timeStamp': '2021-05-21T20:11:28.552804',
              'transcationId': 'd0cf1077-4f7a-41b6-87ea-192fc2ec7205',
              'uploadedBy': 'lalith'},
 'responsetime': '2021-05-21T20:11:28.397Z',
 'version': None}

[2021-05-22 01:41:28,925]
{'errors': [],
 'id': None,
 'metadata': None,
 'response': {'category': 'masterdata',
              'logs': None,
              'operation': 'insert',
              'status': 'COMPLETED',
              'statusDescription': None,
              'successCount': 1,
              'tableName': 'blacklisted_words',
              'timeStamp': '2021-05-21T20:11:28.919447',
              'transcationId': '2f4e9540-4c8e-4d5a-a45c-c87be365f6fb',
              'uploadedBy': 'lalith'},
 'responsetime': '2021-05-21T20:11:28.776Z',
 'version': None}

[2021-05-22 01:41:29,318]
{'errors': [],
 'id': None,
 'metadata': None,
 'response': {'category': 'masterdata',
              'logs': None,
              'operation': 'insert',
              'status': 'FAILED',
              'statusDescription': '[io.mosip.kernel.core.dataaccess.exception.DataAccessLayerException: '
                                   'KER-DAH-001 --> '
                                   'org.hibernate.exception.ConstraintViolationException: '
                                   'could not execute statement; \n'
                                   'nested exception is '
                                   'javax.persistence.PersistenceException: '
                                   'org.hibernate.exceptio]',
              'successCount': 14,
              'tableName': 'machine_spec',
              'timeStamp': '2021-05-21T20:11:29.332605',
              'transcationId': '283aa5e4-4919-49b9-b137-b2abe5d1d939',
              'uploadedBy': 'lalith'},
 'responsetime': '2021-05-21T20:11:29.163Z',
 'version': None}

[2021-05-22 01:41:29,848]
{'errors': [{'errorCode': 'ADM-BLK-002',
             'message': 'invalid field mentioned.The exception occured at line '
                        'number 1'}],
 'id': None,
 'metadata': None,
 'response': None,
 'responsetime': '2021-05-21T20:11:29.893Z',
 'version': None}

[2021-05-22 01:41:30,219]
{'errors': [],
 'id': None,
 'metadata': None,
 'response': {'category': 'masterdata',
              'logs': None,
              'operation': 'insert',
              'status': 'COMPLETED',
              'statusDescription': None,
              'successCount': 1,
              'tableName': 'reason_list',
              'timeStamp': '2021-05-21T20:11:30.231036',
              'transcationId': '5ee18c87-a2cd-4c5f-adec-e46063598a86',
              'uploadedBy': 'lalith'},
 'responsetime': '2021-05-21T20:11:30.086Z',
 'version': None}

[2021-05-22 01:41:30,628]
{'errors': [],
 'id': None,
 'metadata': None,
 'response': {'category': 'masterdata',
              'logs': None,
              'operation': 'insert',
              'status': 'FAILED',
              'statusDescription': '[io.mosip.kernel.core.dataaccess.exception.DataAccessLayerException: '
                                   'KER-DAH-001 --> '
                                   'org.hibernate.exception.ConstraintViolationException: '
                                   'could not execute statement; \n'
                                   'nested exception is '
                                   'javax.persistence.PersistenceException: '
                                   'org.hibernate.exceptio]',
              'successCount': 1,
              'tableName': 'device_type',
              'timeStamp': '2021-05-21T20:11:30.641366',
              'transcationId': '1974a768-2730-4118-b552-d38d304c135f',
              'uploadedBy': 'lalith'},
 'responsetime': '2021-05-21T20:11:30.457Z',
 'version': None}

[2021-05-22 01:41:31,006]
{'errors': [],
 'id': None,
 'metadata': None,
 'response': {'category': 'masterdata',
              'logs': None,
              'operation': 'insert',
              'status': 'FAILED',
              'statusDescription': '[io.mosip.kernel.core.dataaccess.exception.DataAccessLayerException: '
                                   'KER-DAH-001 --> '
                                   'org.hibernate.exception.ConstraintViolationException: '
                                   'could not execute statement; \n'
                                   'nested exception is '
                                   'javax.persistence.PersistenceException: '
                                   'org.hibernate.exceptio]',
              'successCount': 1,
              'tableName': 'user_detail',
              'timeStamp': '2021-05-21T20:11:31.016779',
              'transcationId': 'e11a9f8a-0f9e-49ab-9632-a009c7be333e',
              'uploadedBy': 'lalith'},
 'responsetime': '2021-05-21T20:11:30.868Z',
 'version': None}

[2021-05-22 01:41:31,379]
{'errors': [],
 'id': None,
 'metadata': None,
 'response': {'category': 'masterdata',
              'logs': None,
              'operation': 'insert',
              'status': 'FAILED',
              'statusDescription': '[io.mosip.kernel.core.dataaccess.exception.DataAccessLayerException: '
                                   'KER-DAH-001 --> '
                                   'org.hibernate.exception.ConstraintViolationException: '
                                   'could not execute statement; \n'
                                   'nested exception is '
                                   'javax.persistence.PersistenceException: '
                                   'org.hibernate.exceptio]',
              'successCount': 1,
              'tableName': 'zone_user',
              'timeStamp': '2021-05-21T20:11:31.385824',
              'transcationId': '9225d0e5-324c-41d9-9c5e-e4033f840552',
              'uploadedBy': 'lalith'},
 'responsetime': '2021-05-21T20:11:31.244Z',
 'version': None}

[2021-05-22 01:41:31,804]
{'errors': [],
 'id': None,
 'metadata': None,
 'response': {'category': 'masterdata',
              'logs': None,
              'operation': 'insert',
              'status': 'COMPLETED',
              'statusDescription': None,
              'successCount': 1,
              'tableName': 'id_type',
              'timeStamp': '2021-05-21T20:11:31.793384',
              'transcationId': 'dd17aed4-4b3f-4e0d-92b3-bf163ab082bc',
              'uploadedBy': 'lalith'},
 'responsetime': '2021-05-21T20:11:31.617Z',
 'version': None}

[2021-05-22 01:41:32,173]
{'errors': [],
 'id': None,
 'metadata': None,
 'response': {'category': 'masterdata',
              'logs': None,
              'operation': 'insert',
              'status': 'COMPLETED',
              'statusDescription': None,
              'successCount': 5,
              'tableName': 'loc_hierarchy_list',
              'timeStamp': '2021-05-21T20:11:32.186723',
              'transcationId': '5ea1da26-c4ee-494b-b407-ec14a4a59982',
              'uploadedBy': 'lalith'},
 'responsetime': '2021-05-21T20:11:32.040Z',
 'version': None}

[2021-05-22 01:41:32,412]
{'errors': [{'errorCode': 'ADM-BLK-002',
             'message': 'invalid field mentioned.The exception occured at line '
                        'number 1'}],
 'id': None,
 'metadata': None,
 'response': None,
 'responsetime': '2021-05-21T20:11:32.457Z',
 'version': None}

[2021-05-22 01:41:32,807]
{'errors': [],
 'id': None,
 'metadata': None,
 'response': {'category': 'masterdata',
              'logs': None,
              'operation': 'insert',
              'status': 'FAILED',
              'statusDescription': '[io.mosip.kernel.core.dataaccess.exception.DataAccessLayerException: '
                                   'KER-DAH-001 --> '
                                   'org.hibernate.exception.ConstraintViolationException: '
                                   'could not execute statement; \n'
                                   'nested exception is '
                                   'javax.persistence.PersistenceException: '
                                   'org.hibernate.exceptio]',
              'successCount': 3,
              'tableName': 'doc_type',
              'timeStamp': '2021-05-21T20:11:32.810993',
              'transcationId': '38cdb2f8-7506-4076-8709-fa52f272ecf8',
              'uploadedBy': 'lalith'},
 'responsetime': '2021-05-21T20:11:32.650Z',
 'version': None}

[2021-05-22 01:41:33,188]
{'errors': [],
 'id': None,
 'metadata': None,
 'response': {'category': 'masterdata',
              'logs': None,
              'operation': 'insert',
              'status': 'COMPLETED',
              'statusDescription': None,
              'successCount': 1,
              'tableName': 'module_detail',
              'timeStamp': '2021-05-21T20:11:33.194913',
              'transcationId': '1a418066-942d-45a2-b227-a8ef57eb7007',
              'uploadedBy': 'lalith'},
 'responsetime': '2021-05-21T20:11:33.044Z',
 'version': None}

[2021-05-22 01:41:33,549]
{'errors': [],
 'id': None,
 'metadata': None,
 'response': {'category': 'masterdata',
              'logs': None,
              'operation': 'insert',
              'status': 'FAILED',
              'statusDescription': '[io.mosip.kernel.core.dataaccess.exception.DataAccessLayerException: '
                                   'KER-DAH-001 --> '
                                   'org.hibernate.exception.ConstraintViolationException: '
                                   'could not execute statement; \n'
                                   'nested exception is '
                                   'javax.persistence.PersistenceException: '
                                   'org.hibernate.exceptio]',
              'successCount': 3,
              'tableName': 'device_master',
              'timeStamp': '2021-05-21T20:11:33.567847',
              'transcationId': '7ca9ce8e-8aaa-43c9-a77f-a1daa1f948be',
              'uploadedBy': 'lalith'},
 'responsetime': '2021-05-21T20:11:33.428Z',
 'version': None}

[2021-05-22 01:41:33,903]
{'errors': [],
 'id': None,
 'metadata': None,
 'response': {'category': 'masterdata',
              'logs': None,
              'operation': 'insert',
              'status': 'COMPLETED',
              'statusDescription': None,
              'successCount': 4,
              'tableName': 'machine_type',
              'timeStamp': '2021-05-21T20:11:33.921759',
              'transcationId': '8411bf37-b6bb-4d5b-990f-2adcf97c638a',
              'uploadedBy': 'lalith'},
 'responsetime': '2021-05-21T20:11:33.782Z',
 'version': None}

[2021-05-22 01:41:34,143]
{'errors': [{'errorCode': 'ADM-BLK-002',
             'message': 'invalid field mentioned.The exception occured at line '
                        'number 1'}],
 'id': None,
 'metadata': None,
 'response': None,
 'responsetime': '2021-05-21T20:11:34.187Z',
 'version': None}

[2021-05-22 01:41:34,528]
{'errors': [],
 'id': None,
 'metadata': None,
 'response': {'category': 'masterdata',
              'logs': None,
              'operation': 'insert',
              'status': 'COMPLETED',
              'statusDescription': None,
              'successCount': 1,
              'tableName': 'reason_category',
              'timeStamp': '2021-05-21T20:11:34.540977',
              'transcationId': 'db70302a-0a80-49d9-a0a6-f0834a415d3c',
              'uploadedBy': 'lalith'},
 'responsetime': '2021-05-21T20:11:34.378Z',
 'version': None}

[2021-05-22 01:41:35,168]
{'errors': [],
 'id': None,
 'metadata': None,
 'response': {'category': 'masterdata',
              'logs': None,
              'operation': 'insert',
              'status': 'COMPLETED',
              'statusDescription': None,
              'successCount': 1,
              'tableName': 'template_file_format',
              'timeStamp': '2021-05-21T20:11:35.183219',
              'transcationId': '752cf639-024d-46bc-b3cb-f68c28e01592',
              'uploadedBy': 'lalith'},
 'responsetime': '2021-05-21T20:11:35.032Z',
 'version': None}

[2021-05-22 01:41:35,678]
{'errors': [{'errorCode': 'ADM-BLK-002',
             'message': 'invalid field mentioned.The exception occured at line '
                        'number 1'}],
 'id': None,
 'metadata': None,
 'response': None,
 'responsetime': '2021-05-21T20:11:35.723Z',
 'version': None}

[2021-05-22 01:41:36,040]
{'errors': [],
 'id': None,
 'metadata': None,
 'response': {'category': 'masterdata',
              'logs': None,
              'operation': 'insert',
              'status': 'COMPLETED',
              'statusDescription': None,
              'successCount': 1,
              'tableName': 'title',
              'timeStamp': '2021-05-21T20:11:36.043135',
              'transcationId': '8ebe90a0-3ce9-43e0-bc28-82cec308ed5a',
              'uploadedBy': 'lalith'},
 'responsetime': '2021-05-21T20:11:35.911Z',
 'version': None}
